export const GET_GITHUB_PENDING = 'GET_GITHUB_PENDING'
export const GET_GITHUB_SUCCESS = 'GET_GITHUB_SUCCESS'
export const GET_GITHUB_FAILED = 'GET_GITHUB_FAILED'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
